name: sgr_unity
description: "SGR Unity."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.1.0
  hive: ^4.0.0-dev.2
  image_picker: ^1.1.1
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.19.0
  isar_flutter_libs: ^4.0.0-dev.13
  liquid_swipe: ^3.1.0
  path_provider: ^2.1.0
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.15.0
  quickalert: ^1.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3+1
  supabase_flutter: ^2.5.3
  toastification: ^2.0.0
  uuid: ^4.4.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/SGR_Unity_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/core/utils/assets/
  filename: images.dart
  field_prefix: null

flutter_native_splash:
  color: "#021000"
  android_12:
    color: "#021000"
